# Generated by Django 3.0.4 on 2020-03-12 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('lecture', models.CharField(max_length=256)),
                ('code', models.CharField(max_length=256)),
                ('rate', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('password', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=126)),
                ('code', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=256)),
                ('year', models.CharField(max_length=256)),
                ('semester', models.CharField(max_length=256)),
                ('teacher', models.CharField(max_length=128)),
                ('score', models.IntegerField(default=0)),
            ],
            options={
                'unique_together': {('student_name', 'code', 'year', 'semester', 'teacher')},
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=256)),
                ('year', models.CharField(max_length=256)),
                ('semester', models.CharField(max_length=256)),
                ('teacher', models.CharField(max_length=128)),
            ],
            options={
                'unique_together': {('teacher', 'code', 'year', 'semester')},
            },
        ),
    ]
